import type { Metadata } from "next";
import { Suspense } from "react";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Task-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Suspense fallback={null}>{children}</Suspense>
      </body>
    </html>
  );
}
