import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const SF_PRO = localFont({
  src: [
    {
      path: "../font/sf-pro-display/SFPRODISPLAYMEDIUM.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/sf-pro-display/SFPRODISPLAYBOLD.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Task-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SF_PRO.className} antialiased`}>{children}</body>
    </html>
  );
}
